---
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - jason-rag-network

  api:
    container_name: api
    depends_on:
      - qdrant
    ports:
      - "8000:80"
    networks:
      - jason-rag-network

  ingestion:
    container_name: ingestion
    depends_on:
      - qdrant
    networks:
      - jason-rag-network
    command: ["python", "-m", "ingestion.main"]
    profiles:
      - manual  # only runs when explicitly invoked

  ui:
    container_name: ui
    ports:
      - "8501:8501"
    networks:
      - jason-rag-network

volumes:
  qdrant_data:

networks:
  jason-rag-network:
    driver: bridge
